/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.sfu.federation.viewer.stackviewer;

import ca.sfu.federation.Application;
import ca.sfu.federation.ApplicationContext;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;

/**
 *
 * @author dmarques
 */
public class StackViewerPanel extends JPanel implements Observer {

    /**
     * StackViewerPanel default constructor
     */
    public StackViewerPanel() {
        initComponents();
        Application.getContext().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * Handle update event.
     * @param o Observable
     * @param arg Argument
     */
    public void update(Observable o, Object arg) {
        if (arg instanceof Integer) {
            Integer eventId = (Integer) arg;
            switch (eventId) {
                case ApplicationContext.MODEL_CLOSED:
                    this.jScrollPane1.getViewport().removeAll();
                    break;
                case ApplicationContext.MODEL_LOADED:
                    IContextStackViewerPanel panel = new IContextStackViewerPanel();
                    this.jScrollPane1.setViewportView(panel);
                    break;
            }
        }
    }
    
}
